export const FORMAT_GROUPS = {
  mesh:     { zh: '网格 (Mesh)',      en: 'Mesh' },
  cad:      { zh: 'CAD',              en: 'CAD' },
  animation:{ zh: '动画 (Animation)', en: 'Animation' },
  point:    { zh: '点云 (Point Cloud)',en: 'Point Cloud' },
  volume:   { zh: '体数据 (Volume)',   en: 'Volume' },
  gcode:    { zh: 'GCode',            en: 'GCode' },
  vector:   { zh: '矢量 (Vector)',    en: 'Vector' },
  other:    { zh: '其他',             en: 'Other' },
}

export const RENDER_HINT_LABELS = {
  mesh:       { zh: '标准三角网格渲染', en: 'Standard triangle mesh rendering' },
  volume:     { zh: '体数据渲染',       en: 'Volume rendering' },
  skeleton:   { zh: '骨骼动画渲染',     en: 'Skeleton animation rendering' },
  toolpath:   { zh: '刀具路径渲染',     en: 'Toolpath rendering' },
  pointcloud: { zh: '点云渲染',         en: 'Point cloud rendering' },
  svg:        { zh: '矢量图形渲染',     en: 'Vector graphics rendering' },
}

export const FORMATS = [
  {
    id: 'stl', label: 'STL', extensions: ['.stl'],
    group: 'mesh', renderHint: 'mesh',
    fixture: null, mimeType: null,
    zh: { description: 'STL 是最通用的三角网格格式，广泛用于3D打印和CAD交换。支持 ASCII 和 Binary 两种编码，本应用自动检测并正确加载。' },
    en: { description: 'STL is the most common triangle mesh format, widely used in 3D printing and CAD exchange. Both ASCII and Binary encodings are supported and auto-detected.' },
  },
  {
    id: 'glb', label: 'GLB', extensions: ['.glb'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'AnisotropyBarnLamp.glb', mimeType: 'model/gltf-binary',
    zh: { description: 'GLB 是 glTF 2.0 的二进制格式，将网格、纹理和动画打包在单一文件中。本应用完整支持 PBR 材质、动画和拓扑选择。' },
    en: { description: 'GLB is the binary format of glTF 2.0, packing meshes, textures and animations into a single file. Full PBR material, animation and topology selection support.' },
  },
  {
    id: 'gltf', label: 'GLTF', extensions: ['.gltf'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'AnimatedMorphSphere.gltf', mimeType: 'model/gltf+json',
    zh: { description: 'GLTF 是 glTF 2.0 的 JSON 格式，可引用外部 .bin 和纹理文件。支持 PBR 材质、动画和拓扑选择。' },
    en: { description: 'GLTF is the JSON-based format of glTF 2.0, referencing external .bin and texture files. Supports PBR materials, animations and topology selection.' },
  },
  {
    id: '3mf', label: '3MF', extensions: ['.3mf'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'vise.3mf', mimeType: 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml',
    zh: { description: '3MF 是 3D Manufacturing Format，由 Microsoft 推动的3D打印格式，支持颜色和材质信息。' },
    en: { description: '3MF (3D Manufacturing Format) is a 3D printing format promoted by Microsoft, supporting color and material information.' },
  },
  {
    id: 'step', label: 'STEP', extensions: ['.step', '.stp'],
    group: 'cad', renderHint: 'mesh',
    fixture: 'test-model.step', mimeType: 'application/octet-stream',
    zh: { description: 'STEP 是工业 CAD 领域最常用的三维数据交换格式。本应用自动导入并渲染，保留拓扑结构，支持线框显示和单位自动识别。' },
    en: { description: 'STEP is the most widely used 3D data exchange format in industrial CAD. Auto-imported and rendered with topology preservation, wireframe display and unit auto-detection.' },
  },
  {
    id: 'obj', label: 'OBJ', extensions: ['.obj'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'Cerberus.obj', mimeType: 'text/plain',
    zh: { description: 'OBJ 是经典的 Wavefront 3D 格式，基于文本，可引用外部 .mtl 材质库文件。' },
    en: { description: 'OBJ is the classic Wavefront 3D text-based format, referencing external .mtl material library files.' },
  },
  {
    id: 'ply', label: 'PLY', extensions: ['.ply'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'dolphins_be.ply', mimeType: 'application/octet-stream',
    zh: { description: 'PLY (Polygon File Format) 支持存储顶点颜色和法线等属性，自动检测 ASCII 和 Binary 编码。' },
    en: { description: 'PLY (Polygon File Format) stores vertex colors, normals and other attributes. ASCII and Binary are auto-detected.' },
  },
  {
    id: 'fbx', label: 'FBX', extensions: ['.fbx'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'mixamo.fbx', mimeType: 'application/octet-stream',
    zh: { description: 'FBX 是 Autodesk 的 3D 交换格式，广泛用于游戏和影视行业，支持网格、材质和动画。' },
    en: { description: 'FBX is Autodesk\'s 3D exchange format, widely used in gaming and film industries, supporting meshes, materials and animations.' },
  },
  {
    id: 'dae', label: 'Collada', extensions: ['.dae'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'elf.dae', mimeType: 'application/xml',
    zh: { description: 'DAE (Collada) 是基于 XML 的开放 3D 格式，支持完整的场景图、材质和动画数据。' },
    en: { description: 'DAE (Collada) is an XML-based open 3D format supporting full scene graphs, materials and animation data.' },
  },
  {
    id: '3ds', label: '3DS', extensions: ['.3ds'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'portalgun.3ds', mimeType: 'application/octet-stream',
    zh: { description: '3DS 是 Autodesk 3ds Max 的经典格式，广泛用于老式 3D 内容的交换。' },
    en: { description: '3DS is the classic format of Autodesk 3ds Max, widely used for legacy 3D content exchange.' },
  },
  {
    id: 'usdz', label: 'USDZ', extensions: ['.usdz'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'saeukkang.usdz', mimeType: 'application/octet-stream',
    zh: { description: 'USDZ 是 Apple 的 Universal Scene Description 压缩包格式，用于 AR 和 3D 内容分发。' },
    en: { description: 'USDZ is Apple\'s Universal Scene Description package format for AR and 3D content distribution.' },
  },
  {
    id: 'drc', label: 'Draco', extensions: ['.drc'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'bunny.drc', mimeType: 'application/octet-stream',
    zh: { description: 'DRC (Draco) 是 Google 开发的压缩网格格式，大幅减小 3D 模型文件体积，适合网络传输。' },
    en: { description: 'DRC (Draco) is Google\'s compressed mesh format that significantly reduces 3D model file sizes, ideal for web transmission.' },
  },
  {
    id: 'amf', label: 'AMF', extensions: ['.amf'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'rook.amf', mimeType: 'application/xml',
    zh: { description: 'AMF (Additive Manufacturing Format) 是 ISO 标准的 3D 打印格式，支持颜色、纹理和多种材质。' },
    en: { description: 'AMF (Additive Manufacturing Format) is an ISO standard 3D printing format supporting color, textures and multiple materials.' },
  },
  {
    id: 'lwo', label: 'LWO', extensions: ['.lwo'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'Demo.lwo', mimeType: 'application/octet-stream',
    zh: { description: 'LWO 是 LightWave 3D 的模型格式，支持多边形网格和表面材质属性。' },
    en: { description: 'LWO is LightWave 3D\'s model format, supporting polygon meshes and surface material attributes.' },
  },
  {
    id: '3dm', label: '3DM', extensions: ['.3dm'],
    group: 'mesh', renderHint: 'mesh',
    fixture: 'Rhino_Logo.3dm', mimeType: 'application/octet-stream',
    zh: { description: '3DM 是 Rhinoceros 3D (Rhino) 的原生格式，广泛用于工业设计和建筑领域。' },
    en: { description: '3DM is Rhinoceros 3D (Rhino)\'s native format, widely used in industrial design and architecture.' },
  },
  {
    id: 'bvh', label: 'BVH', extensions: ['.bvh'],
    group: 'animation', renderHint: 'skeleton',
    fixture: 'pirouette.bvh', mimeType: 'text/plain',
    zh: { description: 'BVH (Biovision Hierarchy) 是生物运动捕捉数据格式，以骨架层次结构渲染动画。' },
    en: { description: 'BVH (Biovision Hierarchy) is a motion capture data format, rendered as skeleton hierarchy animations.' },
  },
  {
    id: 'md2', label: 'MD2', extensions: ['.md2'],
    group: 'animation', renderHint: 'mesh',
    fixture: 'ogro.md2', mimeType: 'application/octet-stream',
    zh: { description: 'MD2 是 Quake II 引擎使用的模型格式，支持顶点动画，是经典游戏模型格式。' },
    en: { description: 'MD2 is the model format used by Quake II engine, supporting vertex animation — a classic game model format.' },
  },
  {
    id: 'xyz', label: 'XYZ', extensions: ['.xyz'],
    group: 'point', renderHint: 'pointcloud',
    fixture: 'helix_201.xyz', mimeType: 'text/plain',
    zh: { description: 'XYZ 是简单的点坐标数据格式，每行包含 X/Y/Z 坐标，以点云方式渲染。' },
    en: { description: 'XYZ is a simple point coordinate format with X/Y/Z values per line, rendered as a point cloud.' },
  },
  {
    id: 'pdb', label: 'PDB', extensions: ['.pdb'],
    group: 'point', renderHint: 'pointcloud',
    fixture: 'Al2O3.pdb', mimeType: 'text/plain',
    zh: { description: 'PDB (Protein Data Bank) 是蛋白质结构数据库格式，原子和化学键分别渲染为点云和线段。' },
    en: { description: 'PDB (Protein Data Bank) is the protein structure format. Atoms and bonds are rendered as point clouds and lines.' },
  },
  {
    id: 'pcd', label: 'PCD', extensions: ['.pcd'],
    group: 'point', renderHint: 'pointcloud',
    fixture: 'simple.pcd', mimeType: 'application/octet-stream',
    zh: { description: 'PCD (Point Cloud Data) 是点云库 (PCL) 的标准格式，存储三维点坐标和属性。' },
    en: { description: 'PCD (Point Cloud Data) is Point Cloud Library\'s standard format storing 3D point coordinates and attributes.' },
  },
  {
    id: 'vtk', label: 'VTK', extensions: ['.vtk', '.vtp'],
    group: 'volume', renderHint: 'mesh',
    fixture: 'bunny.vtk', mimeType: 'application/octet-stream',
    zh: { description: 'VTK (Visualization Toolkit) 是科学可视化领域的标准数据格式，支持多种数据类型。' },
    en: { description: 'VTK (Visualization Toolkit) is the standard data format in scientific visualization, supporting multiple data types.' },
  },
  {
    id: 'nrrd', label: 'NRRD', extensions: ['.nrrd'],
    group: 'volume', renderHint: 'volume',
    fixture: 'I.nrrd', mimeType: 'application/octet-stream',
    zh: { description: 'NRRD (Nearly Raw Raster Data) 是医学和科学成像中的体数据格式，支持多维栅格数据。' },
    en: { description: 'NRRD (Nearly Raw Raster Data) is a volume data format in medical and scientific imaging, supporting multi-dimensional raster data.' },
  },
  {
    id: 'gcode', label: 'GCode', extensions: ['.gcode'],
    group: 'gcode', renderHint: 'toolpath',
    fixture: 'benchy.gcode', mimeType: 'text/plain',
    zh: { description: 'GCode 是 3D 打印机的刀具路径指令集，本应用将其中的运动轨迹渲染为三维线段。' },
    en: { description: 'GCode is the instruction set for 3D printer toolpaths. This app renders the movement trajectories as 3D line segments.' },
  },
  {
    id: 'wrl', label: 'VRML', extensions: ['.wrl'],
    group: 'other', renderHint: 'mesh',
    fixture: 'camera.wrl', mimeType: 'text/plain',
    zh: { description: 'WRL (VRML) 是早期的 Web 3D 标准格式，基于文本描述三维场景和物体。' },
    en: { description: 'WRL (VRML) is an early web 3D standard that describes 3D scenes and objects in text format.' },
  },
  {
    id: 'vox', label: 'VOX', extensions: ['.vox'],
    group: 'other', renderHint: 'mesh',
    fixture: 'menger.vox', mimeType: 'application/octet-stream',
    zh: { description: 'VOX 是 MagicaVoxel 体素编辑器格式，以立方体体素构建像素风格的 3D 模型。' },
    en: { description: 'VOX is MagicaVoxel\'s voxel editor format, building pixel-art style 3D models from cubic voxels.' },
  },
  {
    id: 'kmz', label: 'KMZ', extensions: ['.kmz'],
    group: 'other', renderHint: 'mesh',
    fixture: 'Box.kmz', mimeType: 'application/octet-stream',
    zh: { description: 'KMZ 是压缩的 KML (Keyhole Markup Language) 格式，用于地理空间数据和 3D 模型的打包分发。' },
    en: { description: 'KMZ is a compressed KML (Keyhole Markup Language) format for packaging geospatial data and 3D models.' },
  },
]
